### ISSUE TITLE
Did you ever receive an answer from NIST regarding your objections?

### ISSUE THREAD

**Issue by LPhilipp** [NickBorgers/Response-to-NIST-on-MFA#1]
Hi Nick,

I just stumbled upon your E-Mail (Subject: Definition of multi-factor authenticator is problematic) while working through NIST SP 800-63B and was wondering if you ever received an answer from NIST regarding your objections. If so, would it be possible for you to share it with me?

Thanks a lot, in advance.
Best regards
Philipp

**Comment by NickBorgers** [comment]
Hi Philipp,

No, I did not receive any response. I failed to submit this feedback in
time due lack of confidence (NIST is usually the authority I refer to on
such matters), so my email submission occured after their defined deadline.

Regards,
Nick

**Comment by LPhilipp** [comment]
Hi Nick,

i see. Anyway, thank you very much.
Have a nice day.

Regards,
Philipp
